### ISSUE TITLE
Retrieving bundles

### ISSUE THREAD

**Issue by GrbavaCigla** [ankushKun/opensea#2]
I would like to add `Bundles` to this repository, is that feature welcome? Looking at the source code, I found this comment:
```python
    def get_assets(self, owner: str = "", order_by: str = "pk", order_direction: str = "asc", limit: int = 10, verified_only: bool = False):
        #                                                  ^^
        # I dunno what this 'pk' stands for but I think its the default for fastest ordering
```
So, to answer your question, `pk` stands for **P**rimary **K**ey and it is usually used with `id` field in databases (in this case, it means there is no ordering, that's why it is fast).

**Comment by ankushKun** [comment]
I see, thank you very much.

    I would like to add Bundles to this repository, is that feature welcome?
gladly :)

**Comment by GrbavaCigla** [comment]
May I propose some changes to existing code? I don't know why are you using `Assets` as a class.
I am thinking of replacing `Asset` class with a function and splitting `get_assets` to multiple functions (so those functions can be used by new `get_bundles`).

**Comment by ankushKun** [comment]
@GrbavaCigla Sure go ahead :)
This was my first time building a library and I did not pay much attention to the structure :p

Thank you

**Comment by ankushKun** [comment]
@GrbavaCigla Sure go ahead :)
This was my first time building a library and I did not pay much attention to the structure :p

Thank you

**Comment by GrbavaCigla** [comment]
Moving discussion to #7
